service: nuxt-starter
frameworkVersion: '3'
provider:
  name: aws
  stage: dev
  region: ap-southeast-1
  runtime: nodejs18.x
package:
  patterns:
    - '!**'
    - '.output/**'
    
functions:
  NuxtSsrEngine:
    handler: '.output/server/index.mjs'
    url: true